### PR TITLE
Increase timeout to run tests after server start

### PR DESCRIPTION
**Pull request by pmayur**
MongoDB atlas connection takes around 2 secs to get connected, causing tests at the start to fail

### CODE REVIEW

**Comment by RandellDawson** [comment]
@nhcarrigan Instead of adding setTimeout and "hopefully" specifying the "right" time of delay, couldn't we instead detect if the database connection is available before running the tests?

**Comment by nhcarrigan** [comment]
Absolutely. I believe the mongodb package has an `isConnected()` method to validate this.

**Comment by RandellDawson** [comment]
I believe there are other boilerplates with this same setTimeout, so maybe we close this PR and create an issue so someone can contribute a better practice for this?

**Comment by nhcarrigan** [comment]
Agreed.

**Comment by RandellDawson** [comment]
@pmayur Thank you for opening this pull request.

Based on the above discussion, we have decided to create an issue to remove the setTimeout and allow someone to make the preferred fix across all such repos affected.  Once we create the issue with the details of how to make the necessary changes, you are more than welcome to fix all of them with PRs.

Thank you and happy coding.

**Pull request closed without merging**
